#!/usr/bin/env python3
"""Generate Compose files from the USF Compose service catalogue."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
CATALOGUE_PATH = ROOT / "spec/instances/compose-service/service-catalogue.json"
TARGETS = {
    "default": ROOT / "compose.yaml",
    "dev": ROOT / "compose.dev.generated.yaml",
    "test": ROOT / "compose.test.generated.yaml",
    "staging": ROOT / "compose.staging.generated.yaml",
    "production": ROOT / "compose.production.generated.yaml",
}
GENERATED_HEADER = [
    "# Generated by tools/generate-compose/generate-compose.py from spec/instances/compose-service/service-catalogue.json.",
    "# Do not edit by hand. The Compose service catalogue is authoritative.",
]


def load_catalogue(path: Path = CATALOGUE_PATH) -> dict[str, Any]:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def _yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if text == "":
        return '""'
    safe = all(ch.isalnum() or ch in "-_./:" for ch in text)
    if safe and text not in {"true", "false", "null"}:
        return text
    return json.dumps(text)


def _emit_yaml(value: Any, indent: int = 0) -> list[str]:
    pad = " " * indent
    if isinstance(value, dict):
        if not value:
            return [pad + "{}"]
        lines: list[str] = []
        for key, item in value.items():
            if isinstance(item, (dict, list)) and item:
                lines.append(f"{pad}{key}:")
                lines.extend(_emit_yaml(item, indent + 2))
            elif isinstance(item, dict):
                lines.append(f"{pad}{key}: {{}}")
            elif isinstance(item, list):
                if item:
                    lines.append(f"{pad}{key}:")
                    lines.extend(_emit_yaml(item, indent + 2))
                else:
                    lines.append(f"{pad}{key}: []")
            else:
                lines.append(f"{pad}{key}: {_yaml_scalar(item)}")
        return lines
    if isinstance(value, list):
        if not value:
            return [pad + "[]"]
        lines = []
        for item in value:
            if isinstance(item, (dict, list)) and item:
                lines.append(pad + "-")
                lines.extend(_emit_yaml(item, indent + 2))
            elif isinstance(item, dict):
                lines.append(pad + "- {}")
            elif isinstance(item, list):
                lines.append(pad + "- []")
            else:
                lines.append(f"{pad}- {_yaml_scalar(item)}")
        return lines
    return [pad + _yaml_scalar(value)]


def _entries_to_mapping(entries: list[dict[str, str]]) -> dict[str, str]:
    return {entry["name"]: entry["value"] for entry in entries}


def _depends_to_mapping(entries: list[dict[str, str]]) -> dict[str, dict[str, str]]:
    return {entry["serviceName"]: {"condition": entry["condition"]} for entry in entries}


def _service_for_environment(service: dict[str, Any], environment: str) -> dict[str, Any] | None:
    policy = service["environmentPolicies"][environment]
    if not policy["generated"]:
        return None
    compose = service.get("composeService")
    if not compose:
        raise ValueError(f"{service['serviceId']} is generated for {environment} but has no composeService")

    result: dict[str, Any] = {"image": compose["image"]}
    if compose["command"]:
        result["command"] = compose["command"]
    if compose["environment"]:
        result["environment"] = _entries_to_mapping(compose["environment"])
    if compose["ports"]:
        result["ports"] = compose["ports"]
    if compose["volumes"]:
        result["volumes"] = compose["volumes"]
    if compose["dependsOn"]:
        result["depends_on"] = _depends_to_mapping(compose["dependsOn"])
    if compose["healthcheck"]:
        result["healthcheck"] = compose["healthcheck"]
    profiles = policy["composeProfiles"] or compose["profiles"]
    if profiles:
        result["profiles"] = profiles
    return result


def compose_model(catalogue: dict[str, Any], environment: str) -> dict[str, Any]:
    target_env = "dev" if environment == "default" else environment
    services: dict[str, Any] = {}
    volumes: dict[str, Any] = {}
    networks: dict[str, Any] = {}
    external_requirements: list[dict[str, str]] = []

    for service in catalogue["services"]:
        policy = service["environmentPolicies"][target_env]
        compose = _service_for_environment(service, target_env)
        if compose:
            service_name = service["composeService"]["serviceName"]
            services[service_name] = compose
            for volume in service["volumes"]:
                if volume.get("composeVolumeName"):
                    volumes.setdefault(volume["composeVolumeName"], {})
            for network in service["networks"]:
                if network.get("composeNetworkName"):
                    networks.setdefault(network["composeNetworkName"], {})
        elif target_env == "production" and policy["required"] is not False:
            external_requirements.append(
                {
                    "serviceId": service["serviceId"],
                    "realisationMode": policy["realisationMode"],
                    "deploymentForm": policy["deploymentForm"],
                    "proofObligation": policy["proofObligation"],
                }
            )

    model: dict[str, Any] = {
        "name": f"foundation-bootstrap-{target_env}",
        "x-usf-generated": {
            "source": "spec/instances/compose-service/service-catalogue.json",
            "environment": target_env,
        },
        "services": services,
    }
    if volumes:
        model["volumes"] = volumes
    if networks:
        model["networks"] = networks
    if external_requirements:
        model["x-usf-requirements"] = external_requirements
    return model


def render_compose(catalogue: dict[str, Any], environment: str) -> str:
    model = compose_model(catalogue, environment)
    return "\n".join(GENERATED_HEADER + _emit_yaml(model) + [""])


def write_target(environment: str, catalogue: dict[str, Any]) -> Path:
    target = TARGETS[environment]
    target.write_text(render_compose(catalogue, environment), encoding="utf-8")
    return target


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "target",
        nargs="?",
        default="all",
        choices=["all", "default", "dev", "test", "staging", "production"],
    )
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    catalogue = load_catalogue()
    targets = list(TARGETS) if args.target == "all" else [args.target]
    if args.check:
        stale = []
        for target_name in targets:
            path = TARGETS[target_name]
            expected = render_compose(catalogue, target_name)
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual != expected:
                stale.append(str(path.relative_to(ROOT)))
        if stale:
            print(json.dumps({"stale": stale}, indent=2), file=sys.stderr)
            return 1
        return 0

    for target_name in targets:
        path = write_target(target_name, catalogue)
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
